name: nexus_lite_mvp
description: "NEXUS Lite - AI-powered gig marketplace"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.0
  
  # Firebase
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.5.0
  firebase_messaging: ^14.6.0
  
  # JS interop - use newer version
  js: ^0.7.0
  
  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.3.0
  
  # Image & File Handling
  image_picker: ^1.0.0
  cached_network_image: ^3.3.0
  
  # Date & Time
  intl: ^0.19.0
  
  # UI Components
  google_fonts: ^6.0.0
  flutter_rating_bar: ^4.0.1
  
  # Storage
  shared_preferences: ^2.0.0
  
  # Utilities
  uuid: ^4.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
 